# ========================= Tomcat Setting =========================
server:
  port: ${hc.server.port}

# ========================= Spring Setting =========================
spring:
  profiles:
    # This configuration has been in effect since spring-boot 2.4.0
    group:
      dev: log4j2-dev
      prod: log4j2-prod
    include:
      - common
      - knife4j
      - jackson
      - mybatis
      - scheduling
    active: dev
  application:
    name: hc-service-${hc.origin-lowercase-code-name}-${hc.server.port}
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

# ========================= Project Setting =========================
haichuang:
  project-code: ${hc.origin-code-name}
