# ========================= Tomcat Setting =========================
server:
  port: ${hc.server.port}

# ========================= Spring Setting =========================
spring:
  profiles:
    include:
      - common
      - knife4j
      - logback
      - jackson
      - mybatis
      - scheduling
    active: dev
  application:
    name: hc-service-${hc.code-name}-${hc.server.port}
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
