# ========================= Spring Setting =========================
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/data_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      # 初始化时池中建立的物理连接个数
      initial-size: 1
      # 连接池中最小空闲连接数，当连接数少于此值时，连接池会创建连接来补充到该值的数量
      min-idle: 1
      # 连接池中最大的可活跃的连接池数量
      max-active: 20
      stat-view-servlet:
        enabled: true
        # 添加IP白名单, 不进行配置默认只允许本机
        allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        deny:
        # 添加控制台管理用户
        login-username:
        login-password:
      web-stat-filter:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    # 数据库索引, 默认为 [0]
    database: 0
    password:
    lettuce:
      pool:
        # 连接池中最小空闲连接, 默认为 [0]
        min-idle: 0
        # 连接池中最大空闲连接, 默认为 [8]
        max-idle: 8
        # 连接池最大连接数, 默认为 [8]
        max-active: 8
        # 连接池最大阻塞等待时间, 默认为 [-1] 无限制
        max-wait: 10s
    # 连接超时时间
    timeout: 3m
