# ========================= Tomcat Setting =========================
server:
  port: 10001
#  port: ${server.port}

# ========================= Spring Setting =========================
spring:
  profiles:
    include:
      - common
      - knife4j
      - logback
      - jackson
      - mybatis
      - scheduling
    active: dev
  application:
    name: hc-service-main-10001
#    name: hc-service-${haichuang.code-name}-${server.port}
