# ========================= Knife4j Setting =========================
knife4j:
  enable: true
  setting:
    # 重命名SwaggerModel名称
    swaggerModelName: Model列表
    # 是否在每个Debug调试栏后显示刷新变量按钮,默认不显示
    enableReloadCacheParameter: true
    # 是否开启请求参数缓存
    enableRequestCache: false
    # 自定义Footer内容
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: "Powered by <a href='https://www.haichuang.pro'>嗨创软服</a> @2014-2021 HaiChuang Inc."
