# ========================= Spring Setting =========================
spring:
  jackson:
    # 全局设置@JsonFormat的格式pattern
    date-format: 'yyyy-MM-dd HH:mm:ss'
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: LOWER_CAMEL_CASE
    # 当地时区
    locale: zh_CN
    # 设置全局时区
    time-zone: GMT+8
    # 全局设置pojo或被@JsonInclude注解的属性的序列化方式
    default-property-inclusion: NON_NULL
    # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key在SerializationFeature
    serialization:
      # 返回的java.util.date转换成timestamp
      WRITE_DATES_AS_TIMESTAMPS: false
      # 对象为空时是否报错，默认true
      FAIL_ON_EMPTY_BEANS: true
    # 枚举类DeserializationFeature中的枚举属性为key，值为boolean设置jackson反序列化特性,具体key在DeserializationFeature
    deserialization:
      # json中含pojo不存在属性时是否失败报错，默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    # ObjectMapper在jackson中负责json的读写、json与pojo的互转、json tree的互转,具体特性请看MapperFeature，常规默认即可
    mapper:
      # 使用getter取代setter探测属性，如类中含getName()但不包含name属性与setName()，传输的vo json格式模板中依旧含name属性
      USE_GETTERS_AS_SETTERS: true
    # JsonParser在jackson中负责json内容的读取,具体特性在JsonParser.Feature，一般无需设置默认即可
    parser:
      # 是否允许出现单引号，默认false
      ALLOW_SINGLE_QUOTES: false
      #允许出现特殊字符和转义符，默认false
      ALLOW_UNQUOTED_CONTROL_CHARS: false
